### ISSUE TITLE
class Properties　36行目　 instanceof　がなんかおかしいかもしれない？？

### ISSUE THREAD

**Issue by ymgcmnk** [etau/gas-classes#12]
class Properties　36行目
const value = JSON.parse(strValue) instanceof Object ? JSON.parse(strValue) : strValue;　
単純な文字列をぶつけるとJSON変換が入るのでエラーになる？
そういちろうさんに言われるままにコメント書いて見ました。

instanceof
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/instanceof

条件 (三項) 演算子
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

JSON.parse()
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

**Comment by ymgcmnk** [comment]
https://twitter.com/a03/status/1527960938561048576?s=20&t=IPvHgtLUi8IodjRtKxc-Rg

**Comment by etau** [comment]
ありがとう！
仕様変更に対応したコードにしておきました 🤓
